//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ivanov_WPF_EF_MovieCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actors
    {
        public int actor_id { get; set; }
        public string name { get; set; }
        public string age { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string a_country { get; set; }
        public string photo { get; set; }
    }
}
