//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ivanov_WPF_EF_MovieCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorMovie
    {
        public int actor_id { get; set; }
        public int movie_id { get; set; }
    }
}
