//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ivanov_WPF_EF_MovieCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int movie_id { get; set; }
        public string title { get; set; }
        public string m_year { get; set; }
        public Nullable<decimal> budget { get; set; }
        public string m_country { get; set; }
        public string description { get; set; }
        public string poster { get; set; }
    }
}
